"""
Inter-engine data contracts.

This package is the **public interface** between the five subsystems of the framework. No
engine may depend on another engine's internal structures; each depends only on the contract
published here. Specification section 19 states the rule this package exists to enforce:

    No engine may know how another engine works internally. It may only depend on the
    documented contract exposed by that engine.

Contract ownership (specification section 14):

    contract                     producer            consumer
    -------------------------    ----------------    -------------------------
    WorldState                   World Model         Decision Engine
    PlanningContext              Decision layer      AI Engine
    DecisionProposal             AI Engine           Decision Engine
    ActionRequest                Decision Engine     Policy / Execution
    ActionValidationResult       Policy layer        Execution Engine
    ExecutionResult              Execution Engine    Evidence / Decision
    EvidenceSet                  Evidence Engine     World Model / Verification
    VerificationRequest          Evidence / World    Verification Engine
    VerificationResult           Verification Engine World Model
    ExperienceRecord             Experience layer    Experience / Decision

Naming note: :class:`ExperienceRecord` here is the *contract*. The internal storage dataclass
of the same name lives in :mod:`wifi_framework.core.experience.store`; the experience engine
converts between them. Import one of them under an alias when both are in scope.

Design precedents, documented in ``docs/DATA_CONTRACTS.md``:
* envelope shape follows CloudEvents 1.0 (required ``type``/``specversion``/``id``/``source``
  context attributes plus a data payload, with extra context carried as extension attributes);
* versioning follows Semantic Versioning 2.0.0 (major = breaking, minor = compatible addition);
* provenance follows the W3C PROV data model (entity generated by activity, derived from
  inputs).
"""
from __future__ import annotations

from .action import (
    ActionObjective,
    ActionOrigin,
    ActionReason,
    ActionRequest,
    ActionValidationResult,
    ValidationCheckRecord,
    ValidationStatus,
)
from .ai import DecisionProposal, PlanningContext
from .base import METADATA_FIELDS, BaseContract, message_digest
from .common import (
    ArtifactRef,
    EntityRef,
    InterfaceRef,
    ParserRef,
    Provenance,
    TargetType,
    ToolRef,
    to_jsonable,
)
from .envelope import (
    ENVELOPE_SCHEMA,
    ENVELOPE_VERSION,
    ContractEnvelope,
    ContractVersion,
    EngineId,
    format_timestamp,
    new_correlation_id,
    new_message_id,
    parse_timestamp,
    utc_now,
)
from .errors import (
    ContractError,
    ContractOwnershipError,
    ContractValidationError,
    UnknownContractSchema,
    UnsupportedContractVersion,
)
from .evidence import EvidenceSet, Observation, ObservationType
from .execution import ExecutionFailure, ExecutionResult, ExecutionStatus, FailureCategory
from .experience import ActionOutcome, ExecutionOutcomeCost, ExperienceRecord
from .registry import (
    ContractRegistry,
    build_default_registry,
    get_contract_registry,
    reset_contract_registry,
)
from .validation import (
    LEVEL_ORDER,
    CheckStatus,
    ValidationCheck,
    ValidationIssue,
    ValidationLevel,
    ValidationResult,
    require_confidence,
    require_enum,
    require_fields,
    require_type,
)
from .verification import (
    Claim,
    ClaimType,
    EvidenceRequirement,
    VerificationConclusion,
    VerificationMethod,
    VerificationRequest,
    VerificationRequirement,
    VerificationResult,
    VerificationStatus,
)
from .world_state import (
    AccessPointState,
    CapabilityState,
    ClientState,
    HostState,
    HypothesisRef,
    InterfaceState,
    NetworkState,
    ObservationRef,
    UncertaintyRef,
    WorldState,
)

#: Every contract class published by this package, in ownership-table order.
CONTRACTS = (
    WorldState,
    PlanningContext,
    DecisionProposal,
    ActionRequest,
    ActionValidationResult,
    ExecutionResult,
    EvidenceSet,
    VerificationRequest,
    VerificationResult,
    ExperienceRecord,
)

#: Schema name -> version implemented by this build.
SCHEMA_VERSIONS = {contract.SCHEMA: contract.VERSION for contract in CONTRACTS}

__all__ = [
    # envelope / plumbing
    "BaseContract",
    "ContractEnvelope",
    "ContractVersion",
    "EngineId",
    "METADATA_FIELDS",
    "ENVELOPE_SCHEMA",
    "ENVELOPE_VERSION",
    "format_timestamp",
    "parse_timestamp",
    "utc_now",
    "new_message_id",
    "new_correlation_id",
    "message_digest",
    "to_jsonable",
    # errors
    "ContractError",
    "ContractValidationError",
    "UnsupportedContractVersion",
    "UnknownContractSchema",
    "ContractOwnershipError",
    # validation
    "ValidationLevel",
    "ValidationIssue",
    "ValidationCheck",
    "ValidationResult",
    "CheckStatus",
    "LEVEL_ORDER",
    "require_fields",
    "require_type",
    "require_enum",
    "require_confidence",
    # registry
    "ContractRegistry",
    "get_contract_registry",
    "build_default_registry",
    "reset_contract_registry",
    # shared value objects
    "EntityRef",
    "TargetType",
    "Provenance",
    "ArtifactRef",
    "ToolRef",
    "InterfaceRef",
    "ParserRef",
    # contracts
    "WorldState",
    "InterfaceState",
    "AccessPointState",
    "ClientState",
    "HostState",
    "NetworkState",
    "CapabilityState",
    "ObservationRef",
    "HypothesisRef",
    "UncertaintyRef",
    "ActionRequest",
    "ActionReason",
    "ActionObjective",
    "ActionOrigin",
    "ActionValidationResult",
    "ValidationCheckRecord",
    "ValidationStatus",
    "ExecutionResult",
    "ExecutionStatus",
    "ExecutionFailure",
    "FailureCategory",
    "EvidenceSet",
    "Observation",
    "ObservationType",
    "VerificationRequest",
    "VerificationResult",
    "VerificationStatus",
    "VerificationMethod",
    "VerificationRequirement",
    "VerificationConclusion",
    "EvidenceRequirement",
    "Claim",
    "ClaimType",
    "ExperienceRecord",
    "ActionOutcome",
    "ExecutionOutcomeCost",
    "PlanningContext",
    "DecisionProposal",
    "CONTRACTS",
    "SCHEMA_VERSIONS",
]
